use soft_dd;

-- selecionar tabelas EXIBICAO + BUSCA

SELECT * FROM FUNCIONARIOS;
SELECT * FROM AUTENTICACAO;
SELECT * FROM FUNC;
SELECT * FROM PEDIDO_TERMINAL;
SELECT * FROM TERMINAL;
SELECT * FROM TIPO;

SELECT * FROM FUNCIONARIOS
WHERE NOME='FERNANDO';             -- POR NOME

SELECT * FROM FUNCIONARIOS
WHERE ID= 5;                       -- POR ID

SELECT TERMINAL, VALOR FROM TERMINAL WHERE VALOR > 200;
SELECT TERMINAL, VALOR FROM TERMINAL WHERE VALOR > 200 AND VALOR <300;

---------------------------------

SET SQL_SAFE_UPDATES = 0;
/*SET SQL_SAFE_UPDATES = 0; */  -- DESABILITA O SAFE   

---------------------------------

-- INSERIR DADOS NAS TABELAS

INSERT INTO FUNCIONARIO (CODIGO, FUNCIONARIO, TELEFONE) VALUES (1, 'HERBERT', '1111-1111');
INSERT INTO FUNCIONARIO VALUES(2, 'ADEILSON', '1212-1212');

INSERT INTO PEDIDO (CODIGO, FUNC, DATAHORA) VALUES (1, 2, '2021-04-15 11:23:32');

-- ALTERAR NOME DA TABELA + VALORES CONFORME NECESSIDADE


-- ALTERACAO DE DADOS

UPDATE FUNC SET ENDERECO = 'AV. BRASIL, 778' WHERE  CODIGO ='1';             -- INCLUIR DADOS FUNC
UPDATE FUNC SET EMAIL = 'CHAMADOGEEK@GMAIL.com' WHERE CODIGO = '4';          -- SUBSTITUIR DADOS FUNC 
UPDATE TERMINAL SET TERMINAL = '001' WHERE TERMINAL = '002';                 -- ALTERAR NUMERO DO TERMINAL

